### ISSUE TITLE
Inline wat/wasm possible?

### ISSUE THREAD

**Issue by NikVolf** [rustwasm/team#206] opened 2018-07-04 09:57 UTC
For crypto applications, there are requirements for different constant-time functions (where execution time does not depend on input arguments)

AFAIK, with LLVM it is achievable only with inline assembly for target platform

**Comment by xtuc** [comment] 2018-07-04 10:02
Do you mean inlining the module? If yes in what? Or just implemented functions into their callers?

**Comment by NikVolf** [comment] 2018-07-04 10:09
I was thinking of Inlining arbitrary webassembly code with `asm!` macro, it silently fails if used with `wasm32-unknown-unknown` target now

**Comment by sunfishcode** [comment] 2018-07-04 15:16
Support for inline asm in the LLVm was backend is under development; https://reviews.llvm.org/D48183 is one of the recent major steps in that direction.

That said, WebAssembly itself makes no guarantee that any operation is constant time, so it isn't possible to get such guarantees even using inline asm.

**Comment by fitzgen** [comment] 2018-07-05 16:51
Duplicate of https://github.com/rustwasm/team/issues/24 -- closing this issue to consolidate discussion in one place. Thanks for filing @NikVolf !

**Closed by fitzgen** 2018-07-05 16:51 UTC
