### ISSUE TITLE
Should there be an `extern "wasm"` ABI?

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/team#29] opened 2018-01-19 18:43 UTC
It would make compile-time errors if you tried to pass something that can't be passed across FFI boundaries in wasm, but can in C, such as structs.

Maybe this already exists and I'm ignorant of it?

Anyways, if feels weird to expose wasm APIs with `extern "C"`.

**Comment by pepyakin** [comment] 2018-01-19 18:55
I see why are you stating that structs can't pass accross FFI boundaries: wasm can't hold any values other than i32, i64, f32, f64. 
However, "real" architectures usually can't either: on these architectures compiler should split structures between registers and spill into the memory.
So, I don't think that "wasm" is a another ABI.

**Comment by fitzgen** [comment] 2018-01-19 19:04
Other ABIs have defined rules for how to split structs up, and how their parts cross the boundary. Both sides of FFI can agree on how to split up and paste back together structs.

AIUI, wasm does *not* have any such rules, and so you *cannot* pass structs across the boundary because there is no guarantees that both sides will agree on what is being passed and how. For wasm, it would be incorrect for the compiler to allow structs to be used in FFI.

**Comment by pepyakin** [comment] 2018-01-19 19:08
Interesting, I thought contrary to that (at least, in cases where on both sides code is produced by LLVM).

**Comment by alexcrichton** [comment] 2018-01-19 19:32
An interesting question! Makes me wonder a bit more in general about ABI implications in Rust right now.

At the base leve @pepyakin's right, we can only deal with some integers/floats, but another aspect we're not exposing today is the "two level import" where you import from a module and then an item in that module.

That leads me to two questions:

* How do we expose the "two level import" mechanism? Do we want to do this at the language level? Do we want to do this via attributes? A postprocessing for Rust? Note that all `extern` imports are implicitly lumped into an `env` module, but I wouldn't want that to be the case forever.

* What types do we want to allow in imports? Only wasm allowed types? All types and let LLVM figure it out? Wasm, unlike other platforms like x86, (AFAIK) doesn't have a "stable ABI" so when we pass a `struct Foo` around there's no guarantee it's the same as what anyone else does. In that sense I might be inclined to take a very conservative stance for now and restrict imports to just the wasm types until there's a stable ABI that LLVM is implementing.

There's also the question of ABI strings (`"wasm"` and `"C"`) and I'm somewhat tempted to forbid `"C"` and require `"wasm"` on the wasm target...

**Comment by fitzgen** [comment] 2018-01-19 19:39
See also https://github.com/rust-lang/rust/issues/47599

**Comment by fitzgen** [comment] 2018-01-19 19:42
> What types do we want to allow in imports? Only wasm allowed types? ... I might be inclined to take a very conservative stance for now and restrict imports to just the wasm types until there's a stable ABI that LLVM is implementing.

This is what I'd expect.

**Comment by pepyakin** [comment] 2018-01-19 19:46
But what if I would like to actually link to a C code?
Everywhere I would use `extern "C"`, but when I would compile to rust I should use `extern "wasm"`?

**Comment by alexcrichton** [comment] 2018-01-19 19:53
@pepyakin that's true but I also personally have no model for what that even means. Today wasm (in rust at least) has no compilation units, but linking to C code implies some degree of compilation units. In that sense it's difficult to envision what's happening here...

One perhaps reasonable way to rationalize this could be:

* Once we have compilation units, it sounds like they may not be tied to the wasm format. Maybe a stable C ABI will start to emerge? In the meantime LLVM may be the only compiler so we could be good. Perhaps at this point we could say that compilation units communicate over `extern "C"`.
* We would then say that `extern "wasm"` is how you actually import functions from the wasm file itself. These imports cannot be resolved by other compilation units.

That I imagine would help solve communicating with C (assuming everythign works out, again that doesn't really exist yet!) while also being clear about what you're importing from the environment. 

Perhaps then...


```rust
#[module = "foo"] // required for `extern "wasm"`
extern "wasm" {
    fn bar() -> i32; // imported from module "foo"

    // fn baz() -> i8; // illegal
}

extern "C" {
    fn another(); // generates a link error if unresolved and final `.wasm` file is created
}
```

**Comment by sunfishcode** [comment] 2018-01-19 20:01
Yes; we are expecting a stable C ABI to emerge for wasm eventually. In fact, most of the C ABI details in clang are pretty stable already.

The one upcoming C ABI change that is I know of is that when wasm gets [multiple return values](https://github.com/WebAssembly/multi-value), clang will likely switch to passing and returning "small-ish" structs by value (rather than byval/sret in LLVM). After that, it's likely that wasm's C ABI will be stable.

**Comment by pepyakin** [comment] 2018-01-19 20:01
Sounds reasonable!
Also, we shouldn't forget about exports side (approach described by you should work with them well).

> Once we have compilation units, it sounds like they may not be tied to the wasm format. Maybe a stable C ABI will start to emerge? In the meantime LLVM may be the only compiler so we could be good. Perhaps at this point we could say that compilation units communicate over extern "C".

There is [some demand](https://github.com/aturon/rust-wasm/issues/22) for linking against bare wast files (e.g. produced by `wat2wasm`), and I don't know if it is will be supported by LLD. But I guess it should.

**Comment by alexcrichton** [comment] 2018-01-19 20:03
@sunfishcode ah while you're here, do you know if there's an idea of how to specify wasm imports from C? (imports that get hooked into the ES module system, that is)

**Comment by est31** [comment] 2018-01-19 20:56
If there is we could see this as an opportunity to remove the requirement on the `#[no_mangle]` tag: https://github.com/rust-lang/rust/issues/46294

**Comment by sunfishcode** [comment] 2018-01-19 21:33
@alexcrichton Yeah, there are ongoing discussions. The rough theory is:
 - `env` is what you get by default if you don't specify an import module. Symbols in `env` are either resolved at link time, or the linker determines the library that will satisfy them and substitutes it (two-level namespacing). No `env` symbols remain after linking.
 - rename `env` to something less likely to collide with user names
 - add a wasm-specific attribute, which for C/C++ might look like `__attribute__((import_module("foo")))`, for specifying an explicit module name. Functions only, for now. These names would be left untouched by the linker.

**Comment by alexcrichton** [comment] 2018-01-19 22:04
@sunfishcode ok cool, thanks!

That actually aligns pretty well with what I had in mind already, and should work perfectly for us!

**Comment by est31** [comment] 2018-01-21 13:34
> There's also the question of ABI strings ("wasm" and "C") and I'm somewhat tempted to forbid "C" and require "wasm" on the wasm target...

To add to this: I personally  tend to avoid writing out the "C": `extern fn foo` is much nicer. On wasm, this could mean `extern "wasm"` .

**Comment by sunfishcode** [comment] 2018-01-25 05:12
I've now posted https://reviews.llvm.org/D42520 which is an LLVM patch implementing `__attribute__((import_module("foo")))` (C/C++), `"wasm-import-module"="foo"` (LLVM IR), and `.import_module somefunc, foo` (LLVM .s files), and renaming `env`, along what I described above.

**Comment by alexcrichton** [comment] 2018-01-25 16:24
Awesome, thanks for the update @sunfishcode!

**Comment by alexcrichton** [comment] 2018-01-29 18:23
Thinking about this a bit I'd like to bikeshed some possibilities for how we can expose this in Rust. I think there's a big difference in the "desired end state" from what we have today where the wasm module imports/exports are conflated with imports/exports from codegen units. In other words, I think we'll want to consider a sort of "two level namespace" along the lines of:

```rust
#[no_mangle]
pub extern fn foo() {} // exports today, will not export tomorrow

extern {
    fn bar(); // import from the module today, won't tomorrow.
}
```

So with that in mind I'd like to bikeshed two syntaxes for this.

### Add a `"wasm"` ABI

We could take a route of adding the `"wasm"` ABI as a string. It would validate that only valid datatypes  (u32, u64, f32, f64) are contained in the signature and otherwise wouldn't do much else. The above would then be written as:

```rust
#[no_mangle]
pub extern "wasm" fn foo() {} // wasm module export with name `foo`

#[wasm_module = "baz"]
extern "wasm" {
    fn bar(); // wasm module import from `baz` the name of `bar`
}
```

An upside of this approach is that it's somewhat "clean" but a downside is that it still deals with things like `#[no_mangle]` and `pub` for exports and requires some sort of attribute (or thing) like `#[wasm_module]` to declare what module imports come from.

### Only special attributes

A different approach could be to basically just add wasm-specific attributes. This wouldn't change the ABI per se but we could do something like:

```rust
#[wasm_export] // implies `no_mangle`
pub fn foo() {} 

#[wasm_module = "baz"]
extern {
    fn bar();
}
```

We'd still verify that valid datatypes show up in the signature (only u32, u64, f32, f64) but this wouldn't be changing the ABI and rather just adding special attributes

---

Thoughts on this? Other ideas on how to surface imports/exports in Rust?

**Comment by fitzgen** [comment] 2018-01-29 20:58
> We could take a route of adding the "wasm" ABI as a string. It would validate that only valid datatypes (u32, u64, f32, f64) are contained in the signature and otherwise wouldn't do much else

Would we allow pointers and `usize` in the `"wasm"` abi? That would certainly be convenient, but I also understand if folks don't feel great about implicitly converting pointers to `usize` across the `"wasm"` ABI boundary. It is something that works right now, though.

> ```rust
> #[wasm_module = "baz"]
> extern {
>     fn bar();
> }
> ```

Are you imagining this with the future dynamic wasm linking, or with statically linking multiple `.wasm` objects together into a single `.wasm`, or at module instantiation time, or...? What does `wasm_module = "baz"` mean here? What is `"baz"`?

Given what is supported now, I would expect this

> ```rust
> extern {
>     fn bar(); // import from the module today, won't tomorrow.
> }
> ```

to turn into something like this

```rust
#[wasm_import] // we expect to import this at instantiation time, not link to another `.wasm` providing it.
extern "wasm" {
    fn bar();
}
```

> Thoughts on this? Other ideas on how to surface imports/exports in Rust?

Other than the above confusion, this is 💯

**Comment by alexcrichton** [comment] 2018-01-29 22:44
@fitzgen 

> Would we allow pointers and usize in the "wasm" abi? 

Perhaps yeah! I'd personally lean initially towards the ultra-conservative stance of "no" but I'd be fine going in either direction.

> Are you imagining this with the future dynamic wasm linking, or with statically linking multiple .wasm objects together into a single .wasm, or at module instantiation time, or...? 

Ah so to clarify, wasm-the-specification supports something which we're not exporting in Rust right now which is two-level imports. Sort of like in JS where you can do:

```js
import { foo } from 'bar';
```

the module you're importing from here is `bar` and the name you're importing is `foo`. In Rust right now the module is **always** `env` and the name is configurable (it's what you write down in the `extern` block). The `#[wasm_module]` attribute I was alluding to was intended to configure the module name here.

So today you'd write:

```rust
extern {
    fn foo();
}
```

which in JS would be equivalent to:

```js
import { foo } from 'env';
```

which isn't actually what we want! Instead what I'm thinking we'd do is:

```rust
#[wasm_module = "bar"]
extern {
    fn foo();
}
```

which is equivalent to our original js:

```js
import { foo } from 'bar';
```

Does that help clear things up?

**Comment by fitzgen** [comment] 2018-01-30 01:40
> Does that help clear things up?

Yep!

**Comment by mgattozzi** [comment] 2018-01-30 15:42
I feel conflicted on this. On the one hand I like the first one more because

```rust
#[no_mangle]
pub extern "wasm" fn foo() {}
```
is consistent with our current code doing:

```rust
#[no_mangle]
pub extern "c" fn foo() {}
```

I would think we would want to err on the side of consistency for now because it would "Just make sense" to what Rustaceans already know.

That being said I find the:

```rust
#[wasm_export]
pub fn foo() {}
```

To have less noisy syntax and more clearly state what's going in the code, especially for people who might be new to Rust and aren't set in the current FFI conventions. I don't know what I want yet personally out of those choices.

Maybe we could do a compromise:

```rust
#[wasm_export]
pub fn foo() {}
```

implies:

```rust
#[no_mangle]
pub extern "wasm" fn foo() {}
```

and both as valid choices and let the user choose how they want to define it. This does lead to more maintenance burden but we could just have #[wasm_export] just be a proc_macro that desugars to the `pub extern syntax`.

I do think that this:

```rust
#[wasm_module = "bar"]
extern {
    fn foo();
}
```

would be great to avoid putting everything in `env` as one module.

**Comment by CryZe** [comment] 2018-01-30 15:51
Just to clarify a few things
```rust
#[no_mangle]
extern "C" fn foo() { ... }
```
will continue to work just like it does right now, right? Otherwise this proposal will completely wreck my use case.

**Comment by alexcrichton** [comment] 2018-01-30 16:01
@mgattozzi yeah one thing I'm also not sure about with the `"wasm"` ABI is I'm not sure if we actually want it to be a full-blown ABI. But maybe because we're validating types it is indeed an ABI? I'm not sure...

@CryZe I do think we will break that one way or another, yes. Right now we're mixing up linker-like symbols with imports/exports from the wasm module. The intention of this issue/proposal is to make it more explicitly what's happening at the wasm import/export layer (and don't conflate it with symbols).

The functionality isn't being lost though! While today you'd write:

```rust
#[no_mangle]
pub extern "C" fn foo() {}
```

that'd be equivalent to tomorrow's

```rust
#[wasm_export]
pub fn foo() {}
```

(depending on the syntax we settle on)

**Comment by CryZe** [comment] 2018-01-30 16:06
I have a C API that I compile to various targets (39 targets including the WASM target atm). Requiring me to have a full on copy of this C API just for the WASM target is not maintainable for me. So it would be preferable to have a solution that works across various target, loike keeping the behavior of the extern "C" functions, or allowing extern "C" with #[wasm_export] and ignoring that attribute for the other targets.

**Comment by alexcrichton** [comment] 2018-01-30 16:10
Aha an excellent point @CryZe, thanks for the info!

To me that's the nail in the coffin to do:

```rust
#[wasm_export] // implies `no_mangle`, only works with `"C"` ABI functions
pub extern fn foo() {} 

#[wasm_module = "baz"]
extern { // must be "C" ABI
    fn bar();
}
```

We could ignore the `#[wasm_*]` attributes on other targets for sure, but I think it makes sense to start with the C ABI as the definition for "what crosses the module boundary".

@CryZe note that it's also being considered that we should validate signatures with `#[wasm_export]`. For example wasm today only allows u32/u64/f32/f64 at the actual lowest layer. Would this cause problems for you? @fitzgen [pointed out](https://github.com/rust-lang-nursery/rust-wasm/issues/29#issuecomment-361384212) that we could also relax this to pointers/usize as well to make it a bit nicer.

**Comment by mgattozzi** [comment] 2018-01-30 16:50
@alexcrichton I think we should do at least some kind of validation if we can. Unlike #[no_std] removing the std library there's not much we can do to prevent people from using primitives they shouldn't beyond stopping the compiler from finishing the compile. I think this is good behavior to have. I have a feeling we should allow pointers as that's usually how to deal with passing foreign types to other languages but, maybe we can add it at a later date once we get the actual ABI (I think we can call it that in this case) started and hash out the specifics more. We generally go for conservative implementation first than iterate.

**Comment by fitzgen** [comment] 2018-01-30 18:27
I am sympathetic to making cross platform externs work. I think

```rust
#[cfg_attr(target_arch = "wasm32", wasm_import)]
```

should do the trick: 

* allowing reuse of the `extern` declarations, and

* letting `rustc` determine whether this `extern` is for importing functions at wasm module instantiation time vs something provided by another `.wasm` that we will eventually link to.

> @fitzgen pointed out that we could also relax this to pointers/usize as well to make it a bit nicer.

Note that this works *today*, so it is more about if we want it *not* to work anymore.

Also, despite using `extern "C"`, will we check for and allow only scalars? What happens if I try and pass a `repr(C)` struct across the wasm ABI boundary? I think this should be a compilation error, even though it wouldn't be for an `extern "C"` function on other targets.

**Comment by alexcrichton** [comment] 2018-01-30 18:59
@fitzgen hm yeah it's also a good point that we don't have a lot of target-specific attributes today, so something like `wasm_import` *could* work on `x86_64-unknown-linux-gnu` (we just ignore it) but alternatively we could generate a compile error.

I'd also agree yeah, if we have verification I think we'd disallow anything that wasn't literally a float/integer/pointer in FFI, even newtypes.

**Comment by Pauan** [comment] 2018-01-30 20:41
> I'd also agree yeah, if we have verification I think we'd disallow anything that wasn't literally a float/integer/pointer in FFI, even newtypes.

What about newtypes that have the `#[repr(transparent)]` attribute? I think those should be allowed (assuming the wrapped type is allowed).

**Comment by fitzgen** [comment] 2018-01-30 20:43
Given that the whole point of `repr(transparent)` is to allow newtypes to go across FFI boundaries, I think newtypes that are marked with it should be allowed.

**Comment by alexcrichton** [comment] 2018-01-30 20:47
Certainly!

**Comment by est31** [comment] 2018-01-31 05:24
With the current `extern C` system, I can pass pointers around just fine. In fact I'm doing that with strings. So why should there be a problem with pointers? Just do it like with the current `extern C` system, ensure the pointed to types are FFI safe (aka the abi isn't changing in the future) and then accept it.

**Comment by Pauan** [comment] 2018-01-31 12:39
@est31 Will pointers work correctly in both wasm32 and wasm64? What about programs which have been compiled for wasm32 but are being used in a wasm64 environment (or vice versa)?

**Comment by est31** [comment] 2018-01-31 13:40
wasm64 really is a thing? I don't know about you, but I would prefer to not have web pages that suck more than 4 GB of RAM.... but probably we are heading towards that, given the direction the JS ecosystem is trending towards :p. Also yeah for non web embeddings that will probably be very useful.

More seriously, I think linking wasm32 to wasm64 programs simply shouldn't be possible, just as it is not possible to do the same with corresponding native programs. As for two wasm environments talking with each other via js, that is imo the problem of the js layer.

**Comment by Pauan** [comment] 2018-01-31 13:53
@est31 Yes it will be a thing: http://webassembly.org/docs/future-features/#linear-memory-bigger-than-4-gib

> More seriously, I think linking wasm32 to wasm64 programs simply shouldn't be possible

That sounds reasonable to me.

**Comment by alexcrichton** [comment] 2018-02-10 23:12
@sunfishcode I decided to give this a spin today with the support you recently [landed in LLVM](https://reviews.llvm.org/D42520), and the good news is that I've successfully plumbed through the attribute based on blocks in Rust! In other words, I've got this working:

```rust
#[wasm_import_module = "foo"]
extern {
    // all functions here are tagged with the right LLVM attribute
}
```

Unfortunately though it looks like LLD may not be respecting these import module directives? The `*.o` file that rustc feeds into LLD contains:

```
(import "wut" "foo" (func $foo (type 0)))
```

(I'm not good with names)

but the output of LLD only has:

```
(import "env" "foo" (func $foo (type 0)))
```

Do you know if I'm perhaps misconfiguring something? Or is this something that LLD doesn't support just yet?

**Comment by pepyakin** [comment] 2018-02-12 15:29
fyi https://reviews.llvm.org/D42520 has been landed

**Comment by sunfishcode** [comment] 2018-02-12 17:37
@alexcrichton LLD doesn't support it yet.

**Comment by CryZe** [comment] 2018-03-12 04:01
Is it just me or is wasm inherently flawed when it comes to ABIs? The problem here is that the executing environment blindly trusts the function signatures described by the type section in the wasm file to execute, instead of relying on a custom „header file“ that properly describes the function signatures.

The problem really comes down to how limiting the type section is, at least in the wasm mvp. We can only express four different types per argument / return value. That means that we can‘t really express any other types.

bool, u8, i8, u16 and i16 are all smaller than the types we can express there. That‘s not a problem for llvm in general, as it just uses i32 for these types, however it leaves garbage values in the upper bits, which when treated as an i32 value by the executing environment that blindly trusts the type section, such as a browser, then those types won‘t be handled correctly, as those garbage values in the upper bits propagate through into JavaScript‘s number type.

However those aren‘t the only flawed types. u32 and u64 are just as flawed. While they don‘t contain any garbage values, they change their type to i32 and i64 in the function signatures and therefore all values between u31::MAX and u32::MAX get treated as negative numbers and therefore misconverted to JavaScript‘s number type, same thing for u64.

Additionally both i64 and u64 don‘t even fit into JavaScript‘s number type, so i64 is also very flawed, although that‘s only a problem with JavaScript as the executing environment.

We also can‘t use any structs or other more complicated non primitive types.

Therefore the only safe types to use are i32, f32, f64, isize, usize (maybe), pointers and references.

**Comment by steveklabnik** [comment] 2018-03-12 12:12
> The problem here is that the executing environment blindly trusts the function signatures described by the type section in the wasm file to execute, instead of relying on a custom „header file“ that properly describes the function signatures.

Why is a type section "blindly trusting", but a custom header file would be "proper"? I don't see how these would be materially different.

Also, it's not a blind trust; the validate step should typecheck it, as far as I know.

**Comment by CryZe** [comment] 2018-03-12 13:33
This has nothing to do with validation. The problem is essentially that wasm only has 4 types and those are not enough to convey all the semantics. Obviously a header file can lie too, but it‘s not really about lying but about wasm‘s type section being unable to convey information correctly. It‘s similar to the null problem. If you can‘t specify in the type system and automatically generate bindings (like in JavaScript‘s case where it generates an ES6 module from the wasm), then you either have to be conservative and do null checks everywhere or you might get null pointer exceptions everywhere. Maybe a bit of a weird analogy but it‘s mostly exactly that. wasm can only convey i32 in its function signatures. So if you call a `fn foo() -> u32` from JavaScript, then the type section in the wasm file says it returns a i32. JavaScript then treats the value as an i32 and converts it to its number representation, which is a f64. So all positive values that u32 can represent that i32 treats as negative values (0x8000_0000 to 0xFFFF_FFFF) get misconverted by JavaScript to some negative floating point number. That‘s totally fine if the value gets put back into the wasm environment without being interpreted, but if JS actually did interpret it, it would probably cause some bugs, as the value is not the value it‘s supposed to be.

And that‘s all caused because the type section in wasm can‘t convey information about signedness. And the problem here really comes down to that the JS WASM engine relies on this type section to properly conved its information, but it just can‘t, at least at the moment.

This problem doesn‘t just affect signedness though. For types smaller than 32-bit, LLVM keeps garbage in the remaining bits. Since we can only represent 32-bit and 64-bit types in the function signatures, the executing environment doesn‘t know that it shouldn‘t interpret the upper bits. And so on.

Now there is multiple fixes to this:
 - Fix this in the next version of wasm and massively extend what you can represent in function signatures. That‘s the cleanest approach.
 - At imported and exported functions, let the executing environment manually mask garbage bits / reconvert signedness, ... i.e. provide some kind of header file for them to use. This seems like a weird solution as you need to wrap the JS wasm module into another module that does all the fixups.
 - Do most of the fixups on Rust‘s / LLVM‘s side. This means that arguments of imported functions and return values of exported functions need to be treated properly. bool, u8, i8, i16, u16 need to be passed as i32 with instructions inserted to properly mask their bits. u32 needs to be lowered to i64. u64 needs to be lowered as a i64 and a i32. i64 for compatibility reasons with JS (and maybe u64 too) might need to be lowered as two i32 values.
 - Straight up forbid all these types (either warn or error out).

**Comment by Diggsey** [comment] 2018-03-12 15:11
@CryZe calling conventions are a trade-off between power and simplicity. The reason the C calling convention is so successful is because it is (relatively) simple, not because it is powerful, as this makes it easy for other languages to inter-operate with.

> those are not enough to convey all the semantics

Conveying all the semantics is never going to be achievable. You could argue that wasm should support more cases than it currently does, but you should probably ask that of the people developing the spec.

> Straight up forbid all Rust structs, Rust enums, all primitives below 32-bit, all unsigned primitives and possibly i64 too (either warn or error out).

I agree that things not supported by the wasm ABI should be disallowed. Things like 64-bit integers *are* supported by wasm though, and the loss of range due to float conversion is specific to javascript hosts, so it should probably only warn if it's a javascript-specific target.

I think we should develop higher level abstractions for specific environments (see `stdweb`'s approach) to allow passing complex objects, but not necessarily for the general-purpose "wasm" target.

**Comment by sunfishcode** [comment] 2018-03-12 16:12
LLVM has `signext` and `zeroext` argument/result attributes which indicate whether i8/i16/etc. values should be sign/zero-extended to i32 in the output. To the extent that wasm has a C ABI today, the C ABI already avoids garbage bits for bool/i8/u8/i16/u16.

**Comment by CryZe** [comment] 2018-03-12 16:18
So are you saying this just needs to be fixed on rustc's side? Cause at the moment Rust definitely produces garbage when you return those values to Javascript.

**Comment by sunfishcode** [comment] 2018-03-12 16:33
Yes. I've now reported this as https://github.com/rust-lang-nursery/rust-wasm/issues/88.

**Comment by Pauan** [comment] 2018-03-12 21:35
@CryZe The [current (not final) WebAssembly spec](https://webassembly.github.io/spec/js-api/index.html#tojsvalue) mandates that `i64` throws an exception if it is used in JavaScript.

So there will be *no* silent loss of precision. So there is no need for Rust to restrict `i64`.

In addition, that means Rust should *not* lower `u32` to `i64`, because that would prevent using `u32` in JavaScript.

As for supporting `u32` and `u64`, we should discuss with [the WebAssembly design team](https://github.com/WebAssembly/design/issues) about adding in native `u32` and `u64` types.

`stdweb` avoids the issue by converting `u32` to `f64` and then passing the `f64` to JavaScript.

Until WebAssembly gets native `u32` support, Rust can do the same `u32 -> f64` conversion when passing `u32` to WebAssembly. The only other alternative is to not support `u32` at all.

**Comment by pepyakin** [comment] 2018-03-12 21:45
> @CryZe The current (not final) WebAssembly spec mandates that i64 throws an exception if it is used in JavaScript.
> 
> So there will be no silent loss of precision. So there is no need for Rust to restrict i64.

But the problem is that's Rust is used not only in context of JS.

> As for supporting u32 and u64, we should discuss with the WebAssembly design team about adding in native u32 and u64 types.

There is no need for that, since wasm's i32/i64 is inherently signless. Sign is a property of an instruction.

**Comment by Pauan** [comment] 2018-03-12 21:51
> @pepyakin But the problem is that's Rust is used not only in context of JS.

Yes, exactly, which is why I said that Rust should *allow* for passing `i64` to WebAssembly (even though it's not supported by JavaScript).

> There is no need for that, since wasm's i32/i64 is inherently signless. Sign is a property of an instruction.

Yes that's what the WebAssembly spec says, but that means if a programmer passes a `u32` to JavaScript it will receive a negative number even though they passed in a positive number. It's not about the spec, it's about the programmer's intentions and expectations.

**Comment by Pauan** [comment] 2018-03-12 22:11
So, after thinking about this some more, there's two different ways of handling `u32`:

1. In host environments that have native `u32` support it should convert `u32` to `i32` (since as @pepyakin said, in those environments signed-ness doesn't matter). Similarly it should convert `u64` into `i64`.

2. However, for JavaScript it should convert from `u32` to `f64`.

So because the conversion depends upon the host environment, my current thinking is that Rust should simply forbid passing `u32` and `u64` to WebAssembly.

If the programmer knows that the host environment supports native `u32` / `u64` then they can use `foo as i32` or `foo as i64` before passing to WebAssembly.

And in the case of JavaScript the programmer will need to use `foo as f64` before passing to WebAssembly.

**Comment by alexcrichton** [comment] 2018-03-13 21:06
I've [sent a PR](https://github.com/rust-lang/rust/pull/48992) to rust-lang/rust to implement `#[wasm_import_module]`

**Comment by Pauan** [comment] 2018-03-14 03:56
I just [found this](https://github.com/WebAssembly/host-bindings/blob/0ab2d84f35f9b7062693d853aea6055a31defec4/proposals/host-bindings/Overview.md#import-argument-binding-types). It's a part of the host bindings proposal, so it's not standardized yet, but it provides a mechanism for wasm to import/export `u32` (and other types like JS Strings).

So that makes me even more convinced that right now we shouldn't allow for `u32` in wasm import/export. If that host binding proposal gets accepted, *then* we can consider allowing `u32`, but until then we should keep our options open.

**Comment by alexcrichton** [comment] 2018-04-02 21:58
It's now possible in nightly to specify the module of an import via the `#[wasm_import_module]` attribute.

I'm personally sort of tempted to close this as "done" otherwise rather than implement a check for types in the ABI and perhaps investigate a lint at a later date

**Comment by DrSensor** [comment] 2018-06-16 17:49
For example, is it possible to add/use [`Math.random()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random) using `#[wasm_import_module]`?

**Comment by fitzgen** [comment] 2018-06-18 17:21
@DrSensor , `#[wasm_bindgen(wasm_import_module = "...")]` controls the ECMAScript module from which the binding is imported. By default, modules are not used and the global scope is where imports are plucked from.

Essentially, it is whether the generated JS glue looks like

```js
// default
const importedThing = window.importedThing;
```

vs

```js
// using #[wasm_bindgen(wasm_import_module = "./foo")]
import { importedThing } from "./foo";
```

For importing `Math.random`, you would use `#[wasm_bindgen(js_namespace = Math)]` because `Math` is an object on the global, not an ECMAScript module. See https://github.com/rustwasm/wasm-bindgen/tree/master/examples/math for an example.

**Comment by alexcrichton** [comment] 2018-07-18 17:17
It's been awhile since this has come up again and I think in the meantime we've ended up with what seems like a good balance between the various concerns here. Notably the current state of play is:

* No new ABI string is introduced for wasm
* Currently there is no restriction on types used in wasm's ABI, eventually we'll follow the standard of C/Clang/LLVM once it's available.
* Exporting a symbol on wasm is the same as exporting it on other platforms, it's `pub`, reachable, and with an `extern` indicator.
* Importing symbols work the same way as other platforms, with the addition of the `#[link(wasm_import_module = "..")]` ([soon to be merged](https://github.com/rust-lang/rust/pull/52445)) to customize the import module.

Otherwise in the meantime tools like `wasm-bindgen` and `wasm-pack` hide all these details from the user so it's not too too important for ergonomics.

With all that, I'm gonna close this!

**Closed by alexcrichton** 2018-07-18 17:17 UTC

**Comment by dvc94ch** [comment] 2021-11-18 21:12
I wonder if this should be reconsidered. The reason being I think it's useful to use the wasm abi for building ffi's to gc'ed languages.

It's possible to write completely safe ffi apis that express ownership/lifetimes and are ergonomic to write. An example would look like this:

```rust
#[repr(C)]
pub struct Str<'a> {
    ptr: NonNull<u8>,
    len: usize,
    marker: PhantomData<&'a str>,
}

#[no_mangle]
pub unsafe extern "C" fn ffi_new_greeter(greeting: Str<'_>) -> FfiResult<Box<Greeter>> {
    catch_panic(move || {
        Ok(Box::new(Greeter::new(greeting.as_ref().to_string())))
    })
}
```
however when binding it on the other end in gc'ed languages it requires two allocations to call this method, one to allocate the byte buffer, and one to allocate the `Str` struct, and then the `*Str` is passed to the runtime provided `callc` mechanism.

on wasm32, especially interesting with `-Ctarget_feature=+multivalue`, the struct would be passed as two i32 avoiding the allocation. generating bindings for this in other languages would likely also get easier over time as wasm becomes more ubiquos.

**Comment by memoryruins** [comment] 2021-11-21 20:25
> I wonder if this should be reconsidered. 

@dvc94ch looks like it may have been. `#![feature(wasm_abi)]` was added this April https://github.com/rust-lang/rust/pull/83763

**Comment by dvc94ch** [comment] 2021-11-22 10:51
interesting. for now I decided to go with parsing and generating code for "rust header" files after studying various projects for generating ffi interfaces and bindings. I expect [ffi-gen](https://github.com/cloudpeers/ffi-gen) to be released in the next couple of weeks.

**Comment by dvc94ch** [comment] 2021-12-07 22:38
Just released the first version of ffi-gen with support for dart/flutter/node/browser. Still a little lite on documentation, there are cases that can misscompile if you aren't familiar with the internals and errors are very poor. However I think it's currently the best solution out there if you want to create a rust library with bindings to multiple languages. We've already migrated our api to ffi-gen.
