### ISSUE TITLE
Rust Wasm book unclear reference

### ISSUE THREAD

**Issue by hwchen** [rustwasm/team#142] opened 2018-04-18 20:55 UTC
Hello,

In https://github.com/rust-lang-nursery/rust-wasm/blob/master/src/wasm-pack/rust-code.md

the paragraph with `#[no_mangle]` and `pub extern fn` references those two snippets, but I don't see them in the code.

I'm not sure what the paragraph should say; I haven't tried to run the code yet, but if I figure it out I'll make a PR.

Thanks!

**Comment by adityac8** [comment] 2018-06-13 21:52
I have gone through [the link](https://rustwasm.github.io/book/wasm-pack/rust-code.html) but was unable to find `#[no_mangle]` and `pub extern fn` anywhere. @hwchen Correct me if I am wrong.

**Comment by mgattozzi** [comment] 2018-06-14 16:24
I think we fixed this a while back in the book. I'm going to close this for now. @hwchen if the issue is still unlcear or unfixed in the current book could you please open a new issue on [rustwasm/book](https://github.com/rustwasm/book)?

**Closed** 2018-06-14 16:24 UTC
Labels: book

**Comment by hwchen** [comment] 2018-06-27 15:14
Yeah, looks like it was fixed. Thanks!

On Thu, Jun 14, 2018 at 12:24 PM, Michael Gattozzi <notifications@github.com

**Comment by mgattozzi** [comment] 2018-06-27 20:13
Excellent thanks for confirming @hwchen!
