### ISSUE TITLE
Remove unused data segments

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/team#21] opened 2018-01-17 18:43 UTC
I used `wasm-snip` to remove all the panicking and formatting code from my `.wasm`, but my data section is still mostly fragments of diagnostic messages for panicking and formatting, and `wasm-gc` and `wasm-opt` can't remove them.

This is almost 20% of my `.wasm`'s code size.

We need some way to mechanically remove this stuff -- doing it by hand is not feasible.

**Comment by koute** [comment] 2018-01-17 18:53
You can easily remove the data sections automatically; the problem is mostly figuring out which ones you can safely remove, as any references to them in the bytecode look like normal integers, AFAIK.

**Comment by pepyakin** [comment] 2018-01-17 18:58
I think it is hard to solve in general. Segments can be not separated (so you can't always know exact length of data blob) and these integers can be crafted.

**Comment by alexcrichton** [comment] 2018-01-31 01:43
I believe https://github.com/rust-lang-nursery/rust-wasm/issues/2 combined with https://reviews.llvm.org/D42511 should solve this.

**Comment by pepyakin** [comment] 2018-01-31 08:18
@alexcrichton I think there still left this problem https://github.com/rust-lang-nursery/rust-wasm/issues/19#issuecomment-358455513

**Comment by alexcrichton** [comment] 2018-07-18 17:36
Done now that LLD is merged!

**Closed by alexcrichton** 2018-07-18 17:36 UTC
Labels: code size, wasm tooling
