### ISSUE TITLE
The Tutorial seems to be broken

### ISSUE THREAD

**Issue by roydaw** [rustwasm/team#213] opened 2018-07-13 22:51 UTC
After running `npm run serve` I get this error:

```
WARNING in ./wasm_game_of_life.js
36:16-38 "export '__wbindgen_malloc' (imported as 'wasm') was not found in './wasm_game_of_life_bg'
 @ ./wasm_game_of_life.js
 @ ./index.js
 @ ./bootstrap.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 ./bootstrap.js

WARNING in ./wasm_game_of_life.js
44:15-25 "export 'greet' (imported as 'wasm') was not found in './wasm_game_of_life_bg'
 @ ./wasm_game_of_life.js
 @ ./index.js
 @ ./bootstrap.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 ./bootstrap.js

WARNING in ./wasm_game_of_life.js
46:8-28 "export '__wbindgen_free' (imported as 'wasm') was not found in './wasm_game_of_life_bg'
 @ ./wasm_game_of_life.js
 @ ./index.js
 @ ./bootstrap.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 ./bootstrap.js

ERROR in chunk 0
0.bootstrap.js
/home/roy/rustproj/wasm_game_of_life/wasm_game_of_life_bg.wasm
Unexpected valtype: 0x61
````

I inspected my wasm_game_of_lif_bg.wasm and found that all functions were defined. `__wbindgen_malloc`, `greet`, and `__wbindgen_free`.

**Comment by scottrblock** [comment] 2018-07-14 03:31
I'm also receiving the same errors when trying to follow the tutorial. Running on macOS. Happy to provide any other helpful information.

**Comment by xtuc** [comment] 2018-07-15 13:05
The root of the issue `Unexpected valtype: 0x61` comes from https://github.com/xtuc/webassemblyjs, the other errors are from Webpack because we failed to "prepare" the wasm binary.

(I just need to catch my flight and i'll investigate that).

**Comment by xtuc** [comment] 2018-07-18 13:39
I can't reproduce the issue, every chapter of the `wasm_game_of_life` works for me.

**Comment by roydaw** [comment] 2018-07-18 14:50
I tried to start the tutorial again and got hung up at a different point.  I'm trying to follow this page [https://rustwasm.github.io/book/game-of-life/setup.html](url)

This time I wasn't able to build the project with `npm run build-debug`. I get this error:

```
error[E0658]: attribute procedural macros are experimental (see issue #38356)6   
 --> src/lib.rs:7:1
  |
5 | use wasm_bindgen::prelude::*;
  |     ------------------------ procedural macro imported here
6 | 
7 | #[wasm_bindgen]
  | ^^^^^^^^^^^^^^^
  |
  = help: add #![feature(proc_macro)] to the crate attributes to enable
```

I checked my `lib.rs` file and I do have this line:
```
#![feature(proc_macro, wasm_custom_section, wasm_import_module)]
```
So I have no idea why it would do that.
(Using Linux, tried npm 5.5.1 and 5.6.0)

**Comment by data-pup** [comment] 2018-07-18 14:54
Oh shoot, good catch! I think that `proc_macro` needs to be replaced with `use_extern_macros`. Not positive, but I ran into a similar issue recently

**Comment by alexcrichton** [comment] 2018-07-18 14:55
@roydaw ah for that @data-pup is correct, and I've submitted an update to the tutorial at https://github.com/rustwasm/book/pull/48

**Comment by roydaw** [comment] 2018-07-18 15:48
Okay!  I ran `npm update`, and that seemed to fix the issue.

**Comment by alexcrichton** [comment] 2018-07-18 15:50
Ok great! In that case sounds like this is fixed now, so closing

**Closed by alexcrichton** 2018-07-18 15:50 UTC

**Comment by drachehavoc** [comment] 2020-04-28 04:04
same error here, even after execute npm update.
