### ISSUE TITLE
Deprecating or removing rustc-serialize from the ecosystem

### ISSUE THREAD

**Issue by mgattozzi** [rustwasm/team#96] opened 2018-03-26 13:58 UTC
Recently @tomaka [brought this frustrating item up](https://twitter.com/tomaka17/status/978210524348534784) in that we can't compile crates to wasm depending on rustc-serialize. Currently there are [658 crates dependent on it](https://crates.io/crates/rustc-serialize/reverse_dependencies) out of 14k+ crates, but crates.io is limited and doesn't count crates that depend on it through transitive use of other crates, so I'm sure that number is higher than that.

This isn't necessarily just a wasm issue either. With serde being on 1.x and the defacto blessed crate I think we should finally consider what should be done with this crate. It hasn't seen any updates in over a year, is part of the rust-lang-deprecated org, and isn't a community standard anymore. If we want people to have a good experience using Rust getting rid of issues like this is a must.

Thoughts?

**Comment by tomaka** [comment] 2018-03-26 13:59
Merging this PR and publishing version would solve a lot of frustration: https://github.com/rust-lang-deprecated/rustc-serialize/pull/190

**Comment by CryZe** [comment] 2018-03-26 14:03
It isn‘t just rustc-serialize either. Lots of other crates important to the ecosystem like chrono fail to compile too. And that had an outstanding PR that just doesn‘t move ahead as well.

**Comment by tomaka** [comment] 2018-03-26 14:08
In general there are lots of crates that depend on `rustc-serialize` even when it's not useful.

Generally the fix is to make `rustc-serialize` an optional dependency, which is good.
But then in order not to break backward compatibility, `rustc-serialize` is made default, which is good.
But then the problem is that crates generally don't use `default-features = false` on their dependencies, which means that they will pull `rustc-serialize` even when it's unnecessary.

**Comment by mgattozzi** [comment] 2018-03-26 14:08
I know some things there's not much we can do about some crates (i.e. chrono and others) but in the case of the time crate (if it breaks not sure) that chrono depends upon and rustc-serialize that's something possible since it's associated with Rust.

**Comment by est31** [comment] 2018-03-26 14:46
Isn't this something the ecosystem WG could tackle?

**Comment by mgattozzi** [comment] 2018-03-27 14:14
It might be! This is definitely a cross WG concern

**Comment by waywardmonkeys** [comment] 2018-03-27 16:31
Many of the crates listed as reverse dependencies only use it as a dev dependency or as an optional feature ...

**Comment by BelfordZ** [comment] 2018-06-08 17:22
Any workarounds for this? Would really love to compile to web assembly =(

**Comment by alexcrichton** [comment] 2019-02-20 17:40
I'm going to close this since there's not much we can do about this other than helping to update existing crates, which we're already doing.

**Closed by alexcrichton** 2019-02-20 17:40 UTC
